spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8
  datasource:
    name: hello_test
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/hello_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
